version: '3.0'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 8000:8000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  db:
    image: postgres:13
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=saleor
      - POSTGRES_USER=saleor
      - POSTGRES_DB=saleor

  redis:
    image: redis:6
    restart: unless-stopped
    volumes:
      - redis-data:/data

  celery:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A saleor worker --app=saleor.celeryconf:app --loglevel=info
    depends_on:
      - api
      - redis
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

  celery-beat:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: celery -A saleor beat --app=saleor.celeryconf:app --loglevel=info
    depends_on:
      - api
      - redis
    volumes:
      - .:/app
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - DATABASE_URL=${DATABASE_URL}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}

volumes:
  postgres-data:
  redis-data:
